### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by kevinVervier** [diptavo/MultiSKAT#1]
Hi,

I just downloaded the zip file and got this error when running:  `R CMD INSTALL MultiSKAT-master.zip`
```

Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\xce>\x88K\0\0\0\0\0\0\0\0\0\0\0\0\021\0\t\0MultiSKAT-master/UT\005\0\001\xb4\xb5*ZPK\003\004\n\0\0\0\0\0\xce>\x88K_\x91\xc0\x84\t\0\0\0\t\0\0\0\033\0\t\0MultiSKAT-mast'

```

could it be an OS issue? I am currently using Ubuntu 14.04.

Thanks,
Kevin

**Comment by kevinVervier** [comment]
But it worked properly when I cloned the Git repository.

**Comment by diptavo** [comment]
Hi Kevin,

Thanks for noting this.

Sometimes in the older version of Ubuntu, the gsl package is not updated.
This package is a dependency for "copula" R package which in turn is a
pre-requisite for MultiSKAT. I would suggest that you individually install
the dependencies of MultiSKAT if you're facing problems with the
installation, i.e., individually install SKAT, copula and nlme R packages
and then install MultiSKAT.

Please let me know if the problem persists and I will work towards
resolving it.

Thanks,
Diptavo

**Comment by kevinVervier** [comment]
Thank you for the fast answer.
I did install each dependency before trying the `R CMD` command, and got the error `embedded nul in string`.
However, when I tried to install using the `git clone` command, I had not such error.
So it is probably something else than a gsl issue.

**Comment by diptavo** [comment]
Thanks for letting me know.
